# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cba7ede7-b1c9-4ea7-a0d0-53e69ab91c32";
    fsType = "ext4";
  };

  fileSystems."/home/sebastian" = {
    device = "/dev/disk/by-uuid/d4e5eac0-ec5e-40ad-8e5e-5013721f84d0";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-73799172-ec45-441d-9d38-9280e61917fb".device =
    "/dev/disk/by-uuid/73799172-ec45-441d-9d38-9280e61917fb";

  boot.initrd.luks.devices."luks-31c81935-e086-426c-881e-aa8c2a2219be".device =
    "/dev/disk/by-uuid/31c81935-e086-426c-881e-aa8c2a2219be";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5E42-02CD";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3bef8c15-3778-47ce-b8fb-f6df6ea82003"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
